config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
	  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  get 'pages/home'

  get 'pages/men'

  get 'pages/women'

  get 'pages/kids'

  get 'pages/sale'

  get 'pages/aboutAs'

  get 'pages/support'

  root 'pages#home'

	resources :menu
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity = current_item.quantity.blank? ? 1 : current_item.quantity + 1
      Rails.logger.debug(current_item.quantity)
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :product_categories

	has_many :products, through: :product_categories



end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord

	validates :title, presence: true

	has_many :product_categories

	has_many :categories, through: :product_categories

	has_many :line_items, dependent: :destroy

 
  has_attached_file :image, :styles => {:small => "150x150>", :medium => "300x300>", :large => "600x600"} 
	#:url => "/assets/items/:id/:style/:basename.:extension",
	#:path => "rails_root/app/assets/items/:id/:style/:basename.:extension"
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  do_not_validate_attachment_file_type :image

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_variant.rb
class ProductVariant < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart                                              
  before_action :set_cart, only: [:create] 
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
    
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
	extend ActiveSupport::Concern
	private
	def set_cart
		@cart = Cart.find(session[:cart_id])
		current_item.quantity = current_item.quantity.blank? ? 1 : current_item.quantity + 1
 		rescue ActiveRecord::RecordNotFound
		@cart = Cart.create
		session[:cart_id] = @cart.id
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
          product = Product.find(params[:product_id])                             
    @line_item = @cart.line_items.build(product: product)                 

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.all

  end

  def men
  end

  def women
  end

  def kids
  end

  def sale
  end

  def aboutAs
  end

  def support
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%  if notice %>
	<p id="notice"><%= notice %></p>
<% end %>
<h2> Your Pragmatic Cart </h2>
<ul>
	<% @cart.line_items.each do |item| %>
		<li><%= item.product.title %> </li>
	<% end %>
</ul>
<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', carts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Part3rails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="unslider.css">
    <link rel="stylesheet" href="unslider-dots.css">
    <link href='https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed' rel='stylesheet' type='text/css'>

  </head>

  <body>



		<%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>

    

  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item, local: true) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id, id: :line_item_product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id, id: :line_item_cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/pages/aboutAs.html.erb
<h1>Pages#aboutAs</h1>
<p>Find me in app/views/pages/aboutAs.html.erb</p>

app/views/pages/home.html.erb
<div class="my-slider center-block-main">
	<ul>
		<li>
        	<h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
			playmakers, these kicks are ready to stand out.</p>
						<%= image_tag(image_path('slide1.jpg')) %>
            
        </li>
		<li>
        	<h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
			playmakers, these kicks are ready to stand out.</p>
						<%= image_tag(image_path('slide2.jpg')) %>
        </li>
        <li>
        	<h2>RIGHT IS PINK. <br>LEFT IS BLUE</h2>
            <p>Inspired by Brasil’s bold colors and matching up to football’s on-pitch<br>
			playmakers, these kicks are ready to stand out.</p>
						<%= image_tag(image_path('slide3.jpg')) %>
        </li>
	</ul>
</div>

<div class="block3-main center-block-main clearfix">
		<article>
			<%= image_tag(image_path('img31.jpg')) %>
	      <h2><a href="#">FOOTBALL SHOES</a></h2>
	       <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
	  </article>
    <article>
						<%= image_tag(image_path('img32.jpg')) %>
        <h2><a href="#">MODERN CLOTHES</a></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
    </article>
    <article>
						<%= image_tag(image_path('img33.jpg')) %>
        <h2><a href="#">BAGS & ACCESSORIES</a></h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing,
vivamus congue nulla leo, quis imperdiet magna.</p>
    </article>
</div>

<section class="block4-section center-block-main">
	<h2>POPULAR PRODUCTS</h2>

    <div class="block4-main clearfix">
    
       <% @products.each do |product| %>
    	   <article>

    			<%= image_tag product.image.url %>
					<div class="block4-main-content">
						<h2><%= product.title %></h2>
						<h3>здесь должна быть КАТЕГОРИЯ товара</h3>
						<p><%= product.description %></p>
						<p class="price-basket clearfix">
		           	      	<span class="price"><%= product.price %></span>
                            <%= button_to 'Добавить в корзину', line_items_path(product_id: product) %>
		           		     <span class="basket-btn"><a href="#"><%= image_tag(image_path('ico-plus.jpg')) %></a></span>
		                </p>
		           </div>
    	  
            </article>
      <% end %>
 <!--      <article>
						<%= image_tag(image_path('img42.jpg')) %>
            <div class="block4-main-content">
            	<h2>Nike g87</h2>
                <h3>Running Tank Top</h3>
                <p>The Nike Tailwind Loose Women's Running Tank 
Top is made with sweat-wicking fabric to help you 
stay dry and comfortable on your run. Top is made with sweat-wicking fabric to help you 
stay dry and comfortable on your run</p>
				

				<p class="price-basket clearfix">
                	<span class="price">$ 36.99</span>
                    <span class="basket-btn"><a href="#"><%= image_tag(image_path('ico-plus.jpg')) %></a></span>
                </p>
            </div>
        </article>
        <article>
						<%= image_tag(image_path('img43.jpg')) %>
            <div class="block4-main-content">
            	<h2>Nike I-Beam Swoosh</h2>
                <h3>Running Tank Top</h3>
                <p>The Nike Tailwind Loose Women's Running Tank 
Top is made with sweat-wicking fabric to help you 
stay dry and comfortable on your run.</p>

				<p class="price-basket clearfix">
                	<span class="price">$ 36.99</span>
                    <span class="basket-btn"><a href="#"><%= image_tag(image_path('ico-plus.jpg')) %></a></span>
                </p>
            </div>
        </article>
        <article>
						<%= image_tag(image_path('img44.jpg')) %>
            <div class="block4-main-content">
            	<h2>Nike lux</h2>
                <h3>Running Tank Top</h3>
                <p>The Nike Tailwind Loose Women's Running Tank 
Top is made with sweat-wicking fabric to help you 
stay dry and comfortable on your run.</p>

				<p class="price-basket clearfix">
                	<span class="price">$ 36.99</span>
                    <span class="basket-btn"><a href="#"><%= image_tag(image_path('ico-plus.jpg')) %></a></span>
                </p>
            </div>
        </article> -->
    </div>
</section>

<div class="about center-block-main clearfix">
	<article>
    	<h2>About</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam dictum lectus sit amet varius pulvinar. Proin vitae 
dui tincidunt nibh facilisis pellentesque.  Fusce tortor turpis, facilisis ut condimentum eu, sagittis at est.</p>

<p>Praesent egestas posuere urna a egestas. Maecenas facilisis orci vitae ante  tempor accumsan. Aenean aliquam 
justo ac sagittis vehicula. Nam mattis pretium odio sit amet vulputate.</p>

<p>Quisque non lobortis orci. Morbi augue mauris, ultrices at fermentum ac, consequat vitae magna. Pellentesque 
non cursus mi, eu cursus nunc. Nullam  et odio tristique, volutpat urna vitae, dignissim orci. Fusce eu nulla urna.
This template was created by Erik Padamans.</p>

<p>Praesent egestas posuere urna a egestas. Maecenas facilisis orci vitae ante  tempor accumsan. Aenean aliquam 
justo ac sagittis vehicula. Nam mattis pretium odio sit amet vulputate.</p>
 
    </article>
    <div class="map">
    	<div class="mapin">
    		<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d2795.8964773381153!2d27.56055224704729!3d53.895148625930446!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0x0903c79016f027b8!2z0KHRgtCw0LTQuNC-0L0g0JTQuNC90LDQvNC-!5e0!3m2!1sru!2sby!4v1454671639607" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

<div class="subscribe">
	<div class="center-block-main clearfix">
    	<h2><strong>Sign up</strong> for exclusive sales and product news</h2>
        
        <div class="subscribe-form">
        	<form action="" method="get">
            	<input type="email" class="email-inpt" placeholder="eony321v@gmail.com">
              <input type="submit" class="submit-inpt" value="sign up">
            </form>
        </div>
    </div>
</div>

app/views/pages/kids.html.erb
<h1>Pages#kids</h1>
<p>Find me in app/views/pages/kids.html.erb</p>

app/views/pages/men.html.erb
<h1>Анис Классный парень</h1>

app/views/pages/sale.html.erb
<h1>Pages#sale</h1>
<p>Find me in app/views/pages/sale.html.erb</p>

app/views/pages/support.html.erb
<h1>Pages#support</h1>
<p>Find me in app/views/pages/support.html.erb</p>

app/views/pages/women.html.erb
<h1>Pages#women</h1>
<p>Find me in app/views/pages/women.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="ftr">
			<div class="block4-main center-block-main clearfix">
		    	<article>
		        	<h2>Our Stores</h2>
		            <div class="ftr-block-content">
		            	<p>Feel free to visit our stores or contact us.
		                1401 South Grand Avenue 
		                Los Angeles, CA 90015 
		                (213) 748-2411</p>
		                
		                <p>100 Fairview Drive 
		                Franklin, VA 23851 
		                (757) 569-6100 </p>
		            </div>
		        </article>
		        <article>
		        	<h2>Blog posts</h2>
		            <div class="ftr-block-content">
		            	<h3><a href="#">Justin Bieber confirmed that he is gay.</a></h3>
		                <p>Lorem ipsum dolor sit amet, consectetur
		adipiscing elit. Donec sed auctor elit.</p>
						
		                <h3><a href="#">Justin Bieber confirmed that he is gay.</a></h3>
		                <p>Lorem ipsum dolor sit amet, consectetur
		adipiscing elit. Donec sed auctor elit.</p>
		            </div>
		        </article>
		        <article>
		        	<h2>Support</h2>
		            <div class="ftr-block-content">
		            	<p class="support">
		                    <a href="#">Terms & Conditions</a>
		                    <a href="#">FAQ</a>
		                    <a href="#">Payment</a>
		                    <a href="#">Refunds</a>
		                    <a href="#">Track Order</a>
						</p>
		                <p class="support">
		                    <a href="#">Services</a>
		                    <a href="#">Privacy & Security</a>
		                    <a href="#">Careers</a>
		                    <a href="#">Press</a>
		                </p>
		            </div>
		        </article>
		        <article>
		        	<h2>Contact us</h2>
		            <div class="ftr-block-content">
		            	<form>
		                	<input class="ftrmail" type="email" placeholder="your e-mail...">
		                    <textarea class="ftrtext" placeholder="your text..."></textarea>
		                    <input class="ftrsubmit" type="submit" value="Send MESSAGE">
		                </form>
		            </div>
		        </article>
		    </div>
		</footer>

app/views/shared/_header.html.erb
<header>
			<div class="center-block-main">
		    	<div class="header-top clearfix">
		        	<p class="logo">BIRUANG   </p>
		      			 <div class="user_nav">

								<p class="notice"><%= notice %></p>
            		<p class="alert"><%= alert %></p>
						     <% if user_signed_in? %>
						     <%= current_user.email %>, Не Вы?
						     <%= link_to "Выход", destroy_user_session_path, method: :delete %>

						     <% else %>
						     <%= link_to "Регистрация", new_user_registration_path %> | 
						     <%= link_to "Вход", user_session_path %>
						     <% end %>
               </div>


		            <div class="contakt-basket">
		            	<p class="header-phone">
		            		<%= image_tag(image_path('ico-phone.jpg')) %> +371 282 20 760

		              </p>
		                <p class="header-basket">
		                	<%= image_tag(image_path('ico-basket.jpg')) %> $ 99.54 <a href="#">Checkout</a>

		                </p>

		            </div>


		      </div>
		      <div class="header-bottom clearfix">
	        	<nav>
	            	<ul class="menu">
	            			  <li><%= link_to 'Home', pages_home_path %></li>
											<li><%= link_to 'MEN', pages_men_path %></li>
											<li><%= link_to 'woMEN', pages_women_path %></li>                    
											<li><%= link_to 'KIDS', pages_kids_path %></li>	
											<li><%= link_to 'sale', pages_sale_path %></li>
											<li><%= link_to 'ABOUT US', pages_aboutAs_path %></li>
											<li><%= link_to 'SUPPORT', pages_support_path %></li>

	              </ul>
	          </nav>
		            <div class="search-block">
		            	<form action="" method="get">
		                	<input class="search-btn" type="image" <%= image_tag(image_path('search-btn.jpg')) %>
		                    <input type="search" class="search" placeholder="Search...">
		                </form>
		            </div>



		      </div>
		  </div>
		</header>